<?php

namespace ConsultorioBundle\Repository;

/**
 * EspecialidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecialidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
