<?php

namespace ConsultorioBundle\Repository;

/**
 * MedicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicosRepository extends \Doctrine\ORM\EntityRepository
{
}
