<?php

namespace ConsultorioBundle\Repository;

/**
 * PacientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacientesRepository extends \Doctrine\ORM\EntityRepository
{
}
