services:
#    consultorio.example:
#        class: ConsultorioBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.log:
        class: ConsultorioBundle\Services\ServiceLog
        arguments: ["@filesystem"]
