services:
#    consultorio.example:
#        class: ConsultorioBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.log:
        class: ConsultorioBundle\Services\ServiceLog
        arguments: ["@filesystem"]
    app.consultorios:
        class: ConsultorioBundle\Services\ServicesConsultorios
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
